apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJaREZ0YVhSeWFUcG5hSEJmYmsxV2FEbGxWM05tWjNKNU56QlZkMlYzTmt0eVRrcFRZMXA1WnpoYU1rTjZRMlpJIgoJCX0KCX0sCgkiY3JlZHNTdG9yZSI6ICJvc3hrZXljaGFpbiIKfQ==

type: kubernetes.io/dockerconfigjson
